name: Test Azure Federated Credentials

on:
  # Enable manual trigger
  workflow_dispatch:
jobs:
  login:
    runs-on: ubuntu-latest

    # # Set the permissions for the Azure login action
    # environment: azure
    # permissions:
    #   id-token: write # Required for requesting the JWT
    #   contents: read  # Required for listing the commits

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_SP_TESTS_APPID }}
          tenant-id: ${{ secrets.AZURE_SP_TESTS_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID_TESTS }}
